config/routes.rb
Rails.application.routes.draw do
  devise_for :users, only: :omniauth_callbacks, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  scope ":locale", locale: /#{I18n.available_locales.join("|")}/ do
    get "omniauth/:provider" => "omniauth#localized", as: :localized_omniauth
    devise_for :users, skip: :omniauth_callbacks, controllers: {
      registrations: "users/registrations",
      confirmations: "users/confirmations",
    }
    resources :users, only: [:index, :show] do
      get "following" => "users/following#index"
      get "followers" => "users/followers#index"
    end
    resources :books
    resources :reports
    resources :comments, except: [:index, :show]
    resources :friendships, only: [:create, :destroy]
  end
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable, :omniauthable, omniauth_providers: %i(github)
  attr_writer :postcode1, :postcode2
  before_validation :set_postcode
  validates :postcode, format: { with: /\A\d{3}[-]\d{4}\z/, message: "の入力内容を確認してください" }, allow_blank: true
  validates :name, presence: true
  has_many :books, dependent: :destroy
  has_many :reports, dependent: :destroy
  has_many :comments, dependent: :destroy
  paginates_per 10
  has_one_attached :avatar
  has_many :active_relationships, class_name: "Friendship", foreign_key: "follower_id", dependent: :destroy
  has_many :passive_relationships, class_name: "Friendship", foreign_key: "followed_id", dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships
  validate :avatar_validation


  def postcode1
    @postcode1 ||= postcode.present? ? postcode.split("-").first : nil
  end

  def postcode2
    @postcode2 ||= postcode.present? ? postcode.split("-").last : nil
  end

  def self.find_for_github_oauth(auth, signed_in_resource = nil)
    user = User.find_by(provider: auth.provider, uid: auth.uid)
    unless user
      user = User.new(name:     auth.info.name,
                      provider: auth.provider,
                      uid:      auth.uid,
                      email:    auth.info.email,
                      password: Devise.friendly_token[0, 20]
      )
      user.skip_confirmation!
      user.save
    end
    user
  end

  def self.create_unique_string
    SecureRandom.uuid
  end

  def follow(other_user)
    active_relationships.create(followed_id: other_user.id)
  end

  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  def following?(other_user)
    following.include?(other_user)
  end

  private

  def set_postcode
    self.postcode = postcode1.present? || postcode2.present? ? [postcode1, postcode2].join("-") : nil
  end

  def avatar_validation
    if avatar.attached?
      if avatar.blob.byte_size > 10.megabytes
        avatar.purge
        errors.add(:avatar, :max_size_error, max_size: "10MB")
      elsif !avatar.blob.content_type.starts_with?("image/")
        avatar.purge
        errors.add(:avatar, :content_type_error)
      end
    end
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  def after_confirmation_path_for(resource_name, resource)
    if signed_in?(resource_name)
      user_path(resource)
    else
      new_session_path(resource_name)
    end
  end
end

app/controllers/users/followers_controller.rb
class Users::FollowersController < ApplicationController
  def index
    @followers = User.find(params[:user_id]).followers.with_attached_avatar.order("friendships.updated_at DESC").page(params[:page])
  end
end

app/controllers/users/following_controller.rb
class Users::FollowingController < ApplicationController
  def index
    @following = User.find(params[:user_id]).following.with_attached_avatar.order("friendships.updated_at DESC").page(params[:page])
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def github
    @user = User.find_for_github_oauth(request.env["omniauth.auth"], current_user)
    I18n.locale = session[:omniauth_login_locale]

    if @user.persisted?
      set_flash_message(:notice, :success, kind: "GitHub") if is_navigational_format?
      sign_in_and_redirect @user, event: :authentication
    else
      session["devise.github_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  def after_inactive_sign_up_path_for(resource)
    new_user_session_path
  end

  def after_update_path_for(resource)
    user_path(resource)
  end

  def build_resource(hash = {})
    hash[:uid] = User.create_unique_string
    super
  end

  def update_resource(resource, params)
    if params[:password].present? && params[:password_confirmation].present?
      resource.update_attributes(params)
    else
      resource.update_without_password(params)
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.page(params[:page]).with_attached_avatar
  end

  def show
    @user = User.find(params[:id])
  end
end

app/views/users/_follow.html.slim
= form_with model: current_user.active_relationships.build, local: true do |f|
  = f.hidden_field :followed_id, value: user.id
  .actions = f.submit t(".action")

app/views/users/_follow_form.html.slim
- if user != current_user
  - if current_user.following?(user)
    = render partial: "users/unfollow", locals: { user: user }
  - else
    = render partial: "users/follow", locals: { user: user }

app/views/users/_stats.html.slim
= link_to "#{t(".following")}: #{@user.following.count}", user_following_path(@user)
| |
= link_to "#{t(".followers")}: #{@user.followers.count}", user_followers_path(@user)

app/views/users/_unfollow.html.slim
= form_with model: current_user.active_relationships.find_by(followed_id: user.id), method: :delete, local: true do |f|
  .actions = f.submit t(".action")

app/views/users/_user.html.slim
.user
  .user-image
    = image_tag(user.avatar.variant(resize: "50x50")) if user.avatar.attached?
  .user-info
    .user-name = link_to user.name, user_path(user), class: "user-name-link"
    div = user.email
    p = truncate(user.biography, length: 200)

app/views/users/index.html.slim
h1 = t(".users")
.users
  = render partial: "users/user", collection: @users.order(updated_at: :desc), as: :user
= paginate @users

app/views/users/show.html.slim
h1 = t(".profile")
= render partial: "users/follow_form", locals: { user: @user }

table
  tbody
    tr
      th = User.human_attribute_name(:avatar)
      td = image_tag(@user.avatar.variant(resize: "50x50")) if @user.avatar.attached?
    tr
      th = Friendship.model_name.human
      td = render "users/stats"
    tr
      th= User.human_attribute_name(:name)
      td= @user.name
    tr
      th= User.human_attribute_name(:email)
      td= @user.email
    tr
      th= User.human_attribute_name(:postcode)
      td= @user.postcode
    tr
      th= User.human_attribute_name(:address)
      td= @user.address
.user-description
  = simple_format(h(@user.biography), {}, sanitize: false)
= link_to t(".edit"), edit_user_registration_path if @user == current_user