config/routes.rb
Rails.application.routes.draw do
  devise_for :users, only: :omniauth_callbacks, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  scope ":locale", locale: /#{I18n.available_locales.join("|")}/ do
    get "omniauth/:provider" => "omniauth#localized", as: :localized_omniauth
    devise_for :users, skip: :omniauth_callbacks, controllers: {
      registrations: "users/registrations",
      confirmations: "users/confirmations",
    }
    resources :users, only: [:index, :show] do
      get "following" => "users/following#index"
      get "followers" => "users/followers#index"
    end
    resources :books
    resources :reports
    resources :comments, except: [:index, :show]
    resources :friendships, only: [:create, :destroy]
  end
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/book.rb
class Book < ApplicationRecord
  mount_uploader :picture, PictureUploader
  validates :title, presence: true, length: { maximum: 30 }
  validates :memo, presence: true
  paginates_per 10
  has_many :comments, as: :commentable, dependent: :destroy
  belongs_to :user
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:edit, :update, :destroy]

  # GET /books
  def index
    @books = Book.page(params[:page])
  end

  # GET /books/1
  def show
    @book = Book.find(params[:id])
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  def create
    @book = current_user.books.new(book_params)

    if @book.save
      redirect_to @book, notice: t("flash.create", resource: t("activerecord.models.book"))
    else
      render :new
    end
  end

  # PATCH/PUT /books/1
  def update
    if @book.update(book_params)
      redirect_to @book, notice: t("flash.update", resource: t("activerecord.models.book"))
    else
      render :edit
    end
  end

  # DELETE /books/1
  def destroy
    @book.destroy
    redirect_to books_url, notice: t("flash.destroy", resource: t("activerecord.models.book"))
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = current_user.books.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def book_params
      params.require(:book).permit(:title, :memo, :author, :picture)
    end
end

app/views/books/_form.html.slim
= form_for @book do |f|
  = render "error_messages", object: @book
  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :memo
    = f.text_area :memo
  .field
    = f.label :author
    = f.text_field :author
  .field
    = f.label :picture
    = f.file_field :picture, id: :book_picture
  .actions = f.submit

app/views/books/edit.html.slim
h1 = t ".edit_book"

== render 'form'

=> link_to t("show"), @book
'|
=< link_to t("back"), books_path

app/views/books/index.html.slim
h1 = t ".book_list"

table
  thead
    tr
      th = User.human_attribute_name(:avatar)
      th = Book.human_attribute_name(:title)
      th = Book.human_attribute_name(:memo)
      th = Book.human_attribute_name(:author)
      th = Book.human_attribute_name(:picture)
      th = User.human_attribute_name(:name)
      th
      th
      th

  tbody
    - @books.each do |book|
      tr
        td = image_tag(book.user.avatar.variant(resize: "50x50")) if book.user.avatar.attached?
        td = book.title
        td = book.memo
        td = book.author
        td = truncate("#{book.picture}", length: 30)
        td = link_to book.user.name, book.user
        td = link_to t("show"), book
        - if current_user == book.user
          td = link_to t("edit"), edit_book_path(book)
          td = link_to t("destroy"), book, data: { confirm: t("confirm") }, method: :delete

br

.pagination_bottom
  = paginate @books
  = page_entries_info @books

= link_to t(".new_book"), new_book_path

app/views/books/new.html.slim
h1 = t(".new_book")

== render 'form'

= link_to t("back"), books_path

app/views/books/show.html.slim
.book
  .book-title
    strong = "#{Book.human_attribute_name(:title)}:"
    = @book.title
  .book-memo
    strong = "#{Book.human_attribute_name(:memo)}:"
    = @book.memo
  .book-author
    strong = "#{Book.human_attribute_name(:author)}:"
    = @book.author
  .book-image
    strong = "#{Book.human_attribute_name(:picture)}:"
    = image_tag(@book.picture_url) if @book.picture.present?

- if current_user == @book.user
  => link_to t("edit"), edit_book_path(@book)
  '|
=< link_to t("back"), books_path

= render "comments/comments", comments: @book.comments.order(:created_at)