config/routes.rb
Rails.application.routes.draw do
  devise_for :users, only: :omniauth_callbacks, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  scope ":locale", locale: /#{I18n.available_locales.join("|")}/ do
    get "omniauth/:provider" => "omniauth#localized", as: :localized_omniauth
    devise_for :users, skip: :omniauth_callbacks, controllers: {
      registrations: "users/registrations",
      confirmations: "users/confirmations",
    }
    resources :users, only: [:index, :show] do
      get "following" => "users/following#index"
      get "followers" => "users/followers#index"
    end
    resources :books
    resources :reports
    resources :comments, except: [:index, :show]
    resources :friendships, only: [:create, :destroy]
  end
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_locale
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def default_url_options
    { locale: I18n.locale }
  end

  private

  def set_locale
    I18n.locale = params[:locale]
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :postcode1, :postcode2, :address, :biography, :avatar])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :postcode1, :postcode2, :address, :biography, :avatar])
  end

  def after_sign_in_path_for(resource)
    user_path(resource)
  end

  def after_sign_out_path_for(resource)
    new_user_session_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_error_messages.html.slim
- if object.errors.any?
  #error_explanation
    h2 = "#{t("errors.template.header.other", count: object.errors.count, model: object.model_name.human)}:"
    ul
      - object.errors.full_messages.each do |message|
        li = message

app/views/application/_flash.html.slim
- if notice
  p.notice = notice
- if alert
  p.alert = alert

app/views/application/_header.html.slim
header.header
  .header-items-left
    .header-item
      - if Rails.env.development?
        = link_to "メール", letter_opener_web_path
    - if user_signed_in?
      .header-item
        = link_to Book.model_name.human, books_path
      .header-item
        = link_to Report.model_name.human, reports_url
      .header-item
        = link_to User.model_name.human, users_url
  .header-items-right
    - if user_signed_in?
      .header-item
        = link_to "ログアウト", destroy_user_session_path, method: :delete
    - else
      .header-item
        = link_to "ログイン", new_user_session_path
    .header-item
      - if I18n.locale.to_s == "en"
        = link_to "日本語", locale: "ja"
      - else
        = link_to "English", locale: "en"