config/routes.rb
Rails.application.routes.draw do
  devise_for :users, only: :omniauth_callbacks, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  scope ":locale", locale: /#{I18n.available_locales.join("|")}/ do
    get "omniauth/:provider" => "omniauth#localized", as: :localized_omniauth
    devise_for :users, skip: :omniauth_callbacks, controllers: {
      registrations: "users/registrations",
      confirmations: "users/confirmations",
    }
    resources :users, only: [:index, :show] do
      get "following" => "users/following#index"
      get "followers" => "users/followers#index"
    end
    resources :books
    resources :reports
    resources :comments, except: [:index, :show]
    resources :friendships, only: [:create, :destroy]
  end
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/report.rb
class Report < ApplicationRecord
  validates :title, presence: true, length: { maximum: 100 }
  validates :description, presence: true
  has_many :comments, as: :commentable, dependent: :destroy
  paginates_per 10
  belongs_to :user
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_action :set_report, only: [:edit, :update, :destroy]

  # GET /reports
  def index
    @reports = Report.page(params[:page])
  end

  # GET /reports/1
  def show
    @report = Report.find(params[:id])
  end

  # GET /reports/new
  def new
    @report = Report.new
  end

  # GET /reports/1/edit
  def edit
  end

  # POST /reports
  def create
    @report = current_user.reports.new(report_params)

    if @report.save
      redirect_to @report, notice: t("flash.create", resource: t("activerecord.models.report"))
    else
      render :new
    end
  end

  # PATCH/PUT /reports/1
  def update
    if @report.update(report_params)
      redirect_to @report, notice: t("flash.update", resource: t("activerecord.models.report"))
    else
      render :edit
    end
  end

  # DELETE /reports/1
  def destroy
    @report.destroy
    redirect_to reports_url, notice: t("flash.destroy", resource: t("activerecord.models.report"))
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_report
      @report = current_user.reports.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def report_params
      params.require(:report).permit(:title, :description, :reported_on)
    end
end

app/views/reports/_form.html.slim
= form_for @report do |f|
  = render "error_messages", object: @report
  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :reported_on
    = f.date_field :reported_on
  .field
    = f.label :description
    = f.text_area :description, rows: 10
  .actions = f.submit

app/views/reports/edit.html.slim
h1 = t(".edit_report")

== render 'form'

=> link_to t("show"), @report
'|
=< link_to t("back"), reports_path

app/views/reports/index.html.slim
h1 = t(".report_list")

table
  thead
    tr
      th = User.human_attribute_name(:avatar)
      th = Report.human_attribute_name(:title)
      th = Report.human_attribute_name(:description)
      th = Report.human_attribute_name(:reported_on)
      th = User.human_attribute_name(:name)
      th
      th
      th

  tbody
    - @reports.each do |report|
      tr
        td = image_tag(report.user.avatar.variant(resize: "50x50")) if report.user.avatar.attached?
        td = report.title
        td = truncate("#{report.description}", length: 50)
        td = report.reported_on
        td = link_to report.user.name, report.user
        td = link_to t("show"), report
        - if current_user == report.user
          td = link_to t("edit"), edit_report_path(report)
          td = link_to t("destroy"), report, data: { confirm: t("confirm") }, method: :delete

br

.pagination_bottom
  = paginate @reports
  = page_entries_info @reports

= link_to t(".new_report"), new_report_path

app/views/reports/new.html.slim
h1 = t(".new_report")

== render 'form'

= link_to t("back"), reports_path

app/views/reports/show.html.slim
.report
  .report-title
    strong = "#{Report.human_attribute_name(:title)}:"
    = @report.title
  .report-reported_on
    strong = "#{Report.human_attribute_name(:reported_on)}:"
    = @report.reported_on
  .report-description
    strong = "#{Report.human_attribute_name(:description)}:"
    = simple_format(h(@report.description), {}, sanitize: false)

- if current_user == @report.user
  => link_to t("edit"), edit_report_path(@report)
  '|
=< link_to t("back"), reports_path

= render "comments/comments", comments: @report.comments.order(:created_at)